### ISSUE TITLE
Feature 2: Login

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#10]
#### User Story

* As a user, I should be able to login

**Comment by nareshkumar-h** [comment]
![image](https://user-images.githubusercontent.com/2763774/120208982-c0ec9d00-c24b-11eb-9cea-e4c6e489b0c4.png)

Without filling details, user is able to submit form data.

**Comment by krishnaprasadraja** [comment]
I have released my feature
