### ISSUE TITLE
Feature 3: Admin Login

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#11]
#### User Story

* As an admin user, I should be able to login.

**Comment by nareshkumar-h** [comment]
![image](https://user-images.githubusercontent.com/2763774/120209638-8b947f00-c24c-11eb-9dbd-5e7dfc7a66f7.png)

**Comment by nareshkumar-h** [comment]
![image](https://user-images.githubusercontent.com/2763774/120209693-9b13c800-c24c-11eb-88c1-cd0d5669c870.png)

**Comment by krishnaprasadraja** [comment]
I have released this feature
