### ISSUE TITLE
Feature 4: Add Dog 

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#12]
#### User Story

* As an admin user, I should be able to add dogs.

**Comment by nareshkumar-h** [comment]
![image](https://user-images.githubusercontent.com/2763774/120210401-5dfc0580-c24d-11eb-9d8d-7fe136d79552.png)

**Comment by nareshkumar-h** [comment]
![image](https://user-images.githubusercontent.com/2763774/120210651-a5829180-c24d-11eb-9c13-bba606b26e23.png)

**Comment by csys-fresher-batch-2021** [comment]
##### Validations
* Dog age cannot exceed 20 years.

**Comment by csys-fresher-batch-2021** [comment]
##### Clarification Questions 
* What should be the maximum age ?

**Comment by krishnaprasadraja** [comment]
I have released this feature
