### ISSUE TITLE
Feature 5: Delete Dog

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#13]
#### User Story

* As an admin user, I should be able to delete dogs.

**Comment by nareshkumar-h** [comment]
![image](https://user-images.githubusercontent.com/2763774/120210947-feeac080-c24d-11eb-8e77-a58699458fda.png)

**Comment by nareshkumar-h** [comment]
![image](https://user-images.githubusercontent.com/2763774/120210996-0d38dc80-c24e-11eb-96b0-3a7322daf5b3.png)
Not working

**Comment by krishnaprasadraja** [comment]
bug fixed
