### ISSUE TITLE
Code Violation: Credentials Hard Coded

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#26]
#### Code Violation:

* Credentials should not be hardcoded. 
* Best Practice: Use environment variables.

![image](https://user-images.githubusercontent.com/2763774/122842324-c9039e00-d31a-11eb-9e83-b8e2e50540e9.png)

**Comment by krishnaprasadraja** [comment]
I have released this feature
