### ISSUE TITLE
Code Violation: Naming Standards

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#27]
#### Code Violation

* Naming convention not followed.
* 
![image](https://user-images.githubusercontent.com/2763774/122842648-6a8aef80-d31b-11eb-84ce-0e2aabe75d9d.png)
![image](https://user-images.githubusercontent.com/2763774/122842767-9c03bb00-d31b-11eb-93bc-a5391dd6c935.png)

**Comment by krishnaprasadraja** [comment]
I have released this feature
