### ISSUE TITLE
Bug - Feature 1 - User Registration Validation Issues

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#48]
#### Scenario
* I tried to register as a user.
 

#### Issue
*  Unable to register user.

#### Screenshots:
![image](https://user-images.githubusercontent.com/2763774/124339744-1ced6d00-dbce-11eb-8121-4da846e3b606.png)

* Error Message not displayed in the page.

![image](https://user-images.githubusercontent.com/2763774/124339762-35f61e00-dbce-11eb-9ac4-761a7b0ed177.png)

**Comment by nareshkumar-h** [comment]
#### Retested: Registration
* Password Validation Message:  Insufficient Password Length(min 4 and max 10)

#### Issue:
* System accepts 3 characters password
* System accepts above 10 characters password

![image](https://user-images.githubusercontent.com/2763774/124344377-597d9080-dbef-11eb-98e3-09c8f7bd00c8.png)

**Comment by nareshkumar-h** [comment]
#### Bug - Password/Confirm Password mismatch
* System must throw error message if password and confirm password are not same.

**Comment by nareshkumar-h** [comment]
#### Bug: Empty User Name [ Validation is missing ]

* Entered Username as empty

![image](https://user-images.githubusercontent.com/2763774/124348689-057fa580-dc09-11eb-86a0-6891514907c0.png)

![image](https://user-images.githubusercontent.com/2763774/124348696-0e707700-dc09-11eb-8acc-3d89647c6ee3.png)


#### Expected Behavior:
* System must display "Name cannot be empty"

**Comment by nareshkumar-h** [comment]
#### Bug - Same user details should be not registered again.

* System should block duplicate registration.
![image](https://user-images.githubusercontent.com/2763774/124348810-d6b5ff00-dc09-11eb-85b3-8f8519dfbd29.png)

**Comment by krishnaprasadraja** [comment]
feature updated

**Comment by krishnaprasadraja** [comment]
bug fixed
