### ISSUE TITLE
Bug - Feature 2 - Admin Login

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#49]
#### Scenario:
* As a user, I tried to login as an admin user.

#### Issue
* Credentials hardcoded. Need to store login credentials in DB.

#### Screenshot:
![image](https://user-images.githubusercontent.com/2763774/124339877-f67c0180-dbce-11eb-950e-45a4b18fd58d.png)

**Comment by krishnaprasadraja** [comment]
admin user has store  in DB.
