### ISSUE TITLE
Bug- Feature 3: Add Dog

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#50]
#### Scenario
* I tried to add dog.

#### Issue
* Unable to add dog.

#### Screenshot

![image](https://user-images.githubusercontent.com/2763774/124340326-077a4200-dbd2-11eb-9f87-c054bb18254f.png)

![image](https://user-images.githubusercontent.com/2763774/124340380-722b7d80-dbd2-11eb-9e53-92b020ff73cf.png)

Note: I have uploaded the image from my "Downloads" folder.

**Comment by krishnaprasadraja** [comment]
I have updated
