### ISSUE TITLE
Bug - Feature 4: List Dogs

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#51]
#### Scenario :

* As a user, after adding a dog, I want to view the added dogs.

#### Issue:
* Unable to view the added dogs. 

Note: Table has 1 dog details

![image](https://user-images.githubusercontent.com/2763774/124340726-d8b19b00-dbd4-11eb-82c5-a30b0a6ea5bd.png)

#### Screenshots:
![image](https://user-images.githubusercontent.com/2763774/124340698-b1f36480-dbd4-11eb-8e86-cd50b3f65c75.png)

**Comment by krishnaprasadraja** [comment]
I have updated
