### ISSUE TITLE
Bug - Feature 5: Filter Dogs by Price

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#52]
#### Scenario
* As a user, I tried to filter dogs by price.

#### Data Setup for Testing
* Added 3 dogs with different price - 1k,6k,12k

![image](https://user-images.githubusercontent.com/2763774/124341063-6db59380-dbd7-11eb-9d6b-b4a993ded359.png)

#### Issue
* Filters are not working . All the filters are working like price <=5000.

#### Filter 1:  Below 5000 ( works )
![image](https://user-images.githubusercontent.com/2763774/124341081-a8b7c700-dbd7-11eb-976b-8923e70e5bae.png)

#### Filter 2: Between 5000 and 10000 ( Not working - shows wrong results )
![image](https://user-images.githubusercontent.com/2763774/124341104-cdac3a00-dbd7-11eb-8962-3443d562823a.png)

#### Filter 3:  Above 10000 ( Not working - shows wrong results)
![image](https://user-images.githubusercontent.com/2763774/124341127-ec123580-dbd7-11eb-85e3-5cfafc0962a2.png)

**Comment by krishnaprasadraja** [comment]
I have updated
