### ISSUE TITLE
Bug - Feature 6 - Order Dog

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#53]
#### Scenario: 
* As a user, I tried ordering a dog.

#### Issue 1: After login, it shows order page, but unable to enter dogno ( Field is readonly). 

![image](https://user-images.githubusercontent.com/2763774/124341404-b2422e80-dbd9-11eb-9754-3e99c63342e4.png)

#### Screenshots:

![image](https://user-images.githubusercontent.com/2763774/124341441-0baa5d80-dbda-11eb-9ed5-fe7173fa5999.png)

![image](https://user-images.githubusercontent.com/2763774/124341259-c8032400-dbd8-11eb-95bb-3a32f2b96ae8.png)

* Blank Page:   
![image](https://user-images.githubusercontent.com/2763774/124341269-dc472100-dbd8-11eb-87c3-36d61271699a.png)

**Comment by krishnaprasadraja** [comment]
I have updated
