### ISSUE TITLE
Bug- Feature 7:  Accept/Reject Orders

### ISSUE THREAD

**Issue by nareshkumar-h** [csys-fresher-batch-2021/breeddogsapp-krishna#54]
#### Scenario
* As an admin user, I tried to accept and reject an order.

#### Issue 1:
* After accepting order, still admin is able to reject an order.
* After rejecting order, still admin is able to accept an order.

#### Issue 2: Duplicate Order
* Current Behavior : Multiple users is able to order the same dog. 
* Expected Behavior: Once user booked a dog, other user should not be able to order the same dog.

#### Issue 3: Dog Details are not displayed
* Currently  only dogno is displayed

#### Screenshots
![image](https://user-images.githubusercontent.com/2763774/124341870-38ac3f80-dbdd-11eb-87ec-ecff2a8bd9ac.png)

**Comment by krishnaprasadraja** [comment]
After accepting also admin wants a control to reject order because It is an cash on deliver.
